### ISSUE TITLE
[Bug] Compilation error with Angular 13

### ISSUE THREAD

**Issue by marko164** [codex-team/editor.js#1826]
```
Error: node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:9 - error TS2614: Module '"codex-tooltip"' has no exported member 'TooltipContent'. Did you mean to use 'import TooltipContent from "codex-tooltip"' instead?

Error: node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:25 - error TS2614: Module '"codex-tooltip"' has no exported member 'TooltipOptions'. Did you mean to use 'import TooltipOptions from "codex-tooltip"' instead?
```

Steps to reproduce:
1. ```import EditorJS from '@editorjs/editorjs';```
2. ```this._editor = new EditorJS({holder: this.id});```

Editor.js version: 2.22.2

Angular version: 13.0.2

Plugins you use with their versions: none

**Comment by susana-bit** [comment]
Same issue after upgrade Angular form 10 to 11.
Editor.js: 2.20.2
Codex-tooltip: 1.0.1 to 1.0.4

**Comment by ghost** [comment]
I have same issue.
Editor.js: 2.21.0
Angular: 11

**Comment by BunoKertez** [comment]
same issue here
Angular 12
Editor 2.22.2

editing the node module file to this fixed it for me, not ideal:
node_modules\@editorjs\editorjs\types\api\tooltip.d.ts

```
//import {TooltipContent, TooltipOptions} from 'codex-tooltip';
import TooltipOptions from "codex-tooltip"
import TooltipContent from "codex-tooltip"
```

**Comment by Ayman-Alahmad** [comment]
same issue.
Editor.js: 2.22.2
Angular: ~13.1.0

**Comment by IamDeshRaj** [comment]
same issue.
Editor.js: 2.22.2
Angular: ~13.1.0

**Comment by Marax** [comment]
specifying version of codex-tooltip: 1.0.2 in package.json solves the issue for me on Angular 13.1

**Comment by Krishnagupta0568** [comment]
Error: node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:9 - error TS2614: Module '"codex-tooltip"' has no exported member 'TooltipContent'. Did you mean to use 'import TooltipContent from "codex-tooltip"' 
instead?

Solution Of This 
Change in node_modules/@editorjs/editorjs/types/api/tooltip.d.ts file.
Replace this line
import {TooltipContent, TooltipOptions} from 'codex-tooltip';
to these
import { TooltipContent } from 'codex-tooltip/dist/types';
import { TooltipOptions } from 'codex-tooltip/dist/types';

**Comment by liaozhangpeng** [comment]
same issue with angular 11

**Comment by IamDeshRaj** [comment]
@liaozhangpeng work around will be, just open the downloaded package of editorjs and edit node_modules@editorjs\editorjs\types\api\tooltip.d.ts as mentioned below and mentioned by @BunoKertez [here](https://github.com/codex-team/editor.js/issues/1826#issuecomment-989852612)


`//import {TooltipContent, TooltipOptions} from 'codex-tooltip';
import TooltipOptions from "codex-tooltip"
import TooltipContent from "codex-tooltip"`

**Comment by PhotonicDev** [comment]
```
const fs = require('fs-extra')

fs.readFile('node_modules/@editorjs/editorjs/types/api/tooltip.d.ts', {
  encoding: 'utf-8',
}).then(brokenFile => {
  const fixedFile = brokenFile.replace(
    `import {TooltipContent, TooltipOptions} from 'codex-tooltip';`,
    `import TooltipOptions from "codex-tooltip"\n
import TooltipContent from "codex-tooltip"`
  )
  console.log(fixedFile)
  fs.writeFile(
    'node_modules/@editorjs/editorjs/types/api/tooltip.d.ts',
    fixedFile,
    { encoding: 'utf-8' }
  )
})
```
Here's a fix using fs-extra, not necessary to use fs-extra, just used it for convenience you can rewrite it to regular fs libs, I used this script since it broke before holidays just to be able to use the editor.js, please patch this.

**Comment by BrentonScott** [comment]
Any update on this? Still find the same error on 2.23.1

**Comment by liaozhangpeng** [comment]
> Any update on this? Still find the same error on 2.23.1

codex-tooltip version 1.0.2 will temporarily solve this problem

add this to your package.json

"resolutions": {
"codex-tooltip": "1.0.2"
}

then
yarn or npm install

**Comment by keyone2693z** [comment]
same issue ver 2.23.2

**Comment by Stajor** [comment]
Same issue
Angular: 13
Editorjs: 2.23.2

```
Error: node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:9 - error TS2614: Module '"codex-tooltip"' has no exported member 'TooltipContent'. Did you mean to use 'import TooltipContent from "codex-tooltip"' instead?

import {TooltipContent, TooltipOptions} from 'codex-tooltip';


Error: node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:25 - error TS2614: Module '"codex-tooltip"' has no exported member 'TooltipOptions'. Did you mean to use 'import TooltipOptions from "codex-tooltip"' instead?

import {TooltipContent, TooltipOptions} from 'codex-tooltip';
```

**Comment by neSpecc** [comment]
Seems solved
